"""empty message

Revision ID: 93b5c197c04d
Revises: 
Create Date: 2024-10-17 10:15:13.958701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b5c197c04d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('your_table_name')
    op.drop_table('health_statistics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_statistics',
    sa.Column('id', sa.FLOAT(), nullable=True),
    sa.Column('State', sa.TEXT(), nullable=True),
    sa.Column('District', sa.TEXT(), nullable=True),
    sa.Column('Latitude', sa.FLOAT(), nullable=True),
    sa.Column('Longitude', sa.FLOAT(), nullable=True),
    sa.Column('TB Incidence', sa.FLOAT(), nullable=True),
    sa.Column('Diabetes ', sa.FLOAT(), nullable=True),
    sa.Column('Malaria Incidence', sa.FLOAT(), nullable=True),
    sa.Column('HIV/AIDS', sa.FLOAT(), nullable=True),
    sa.Column('IMR', sa.FLOAT(), nullable=True),
    sa.Column('Vaccination ', sa.FLOAT(), nullable=True),
    sa.Column('Income (INR)', sa.FLOAT(), nullable=True),
    sa.Column('Employment Rate', sa.FLOAT(), nullable=True),
    sa.Column('Education ', sa.FLOAT(), nullable=True),
    sa.Column('Housing', sa.FLOAT(), nullable=True),
    sa.Column('Urbanization ', sa.FLOAT(), nullable=True),
    sa.Column('AQI', sa.FLOAT(), nullable=True),
    sa.Column('Annual Rainfall (mm)', sa.FLOAT(), nullable=True),
    sa.Column('Target (Healthcare Access)', sa.FLOAT(), nullable=True)
    )
    op.create_table('your_table_name',
    sa.Column('id', sa.BIGINT(), nullable=True),
    sa.Column('State', sa.TEXT(), nullable=True),
    sa.Column('District', sa.TEXT(), nullable=True),
    sa.Column('Latitude', sa.FLOAT(), nullable=True),
    sa.Column('Longitude', sa.FLOAT(), nullable=True),
    sa.Column('TB Incidence', sa.FLOAT(), nullable=True),
    sa.Column('Diabetes ', sa.FLOAT(), nullable=True),
    sa.Column('Malaria Incidence', sa.FLOAT(), nullable=True),
    sa.Column('HIV/AIDS', sa.FLOAT(), nullable=True),
    sa.Column('IMR', sa.FLOAT(), nullable=True),
    sa.Column('Vaccination ', sa.FLOAT(), nullable=True),
    sa.Column('Income (INR)', sa.FLOAT(), nullable=True),
    sa.Column('Employment Rate', sa.FLOAT(), nullable=True),
    sa.Column('Education ', sa.FLOAT(), nullable=True),
    sa.Column('Housing', sa.FLOAT(), nullable=True),
    sa.Column('Urbanization ', sa.FLOAT(), nullable=True),
    sa.Column('AQI', sa.FLOAT(), nullable=True),
    sa.Column('Annual Rainfall (mm)', sa.FLOAT(), nullable=True),
    sa.Column('Target (Healthcare Access)', sa.BIGINT(), nullable=True)
    )
    # ### end Alembic commands ###
